### ISSUE TITLE
NoMethodError in 0.4.5

### ISSUE THREAD

**Issue by zsong** [travisjeffery/timecop#37]
Failure/Error: Timecop.freeze(Date.new(2012, 6, 9)) do
NoMethodError:
  undefined method `local' for nil:NilClass

But this code works in 0.3.5.
